### ISSUE TITLE
依赖包缺失很多啊

### ISSUE THREAD

**Issue by hackyun** [dxer/hbase-sql#1]
缺失很多依赖包，导入工程就报错

**Comment by dxer** [comment]
这个是maven项目哦

**Comment by hackyun** [comment]
是的，少了sql解析的相关依赖。

**Comment by dxer** [comment]
<dependency>
            <groupId>net.sf.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>
            <version>0.7.0</version>
        </dependency>

sql解析用的是jsqlparser

**Comment by hackyun** [comment]
测试类里面缺了 druid ，还缺fastjson 等。很多包。另外导入工程之后jdk是1.5的。

**Comment by dxer** [comment]
额，应该是忘记提交了，你可以先把出错的类注释掉

**Comment by hackyun** [comment]
报红叉的实在太多了，要不然你更新一下版本库？ 我导下来测试看。 我感觉你是不是换过一次命名空间，还是本身的引用出错？

**Comment by dxer** [comment]
刚更新了
